// This file is auto-generated — do not edit manually.
import type { IkasProduct } from "@ikas/bp-storefront";

export interface Props {
  /** PDP ana ürün objesi */
  product?: IkasProduct | null;
  /** Bölüm zemin rengi */
  backgroundColor?: string;
  seriesTag?: string;
  productBadge?: string;
  sizeGuideText?: string;
  stockInText?: string;
  stockOutText?: string;
  addToCartText?: string;
  addingToCartText?: string;
  addedToCartText?: string;
  soldOutText?: string;
  discountBadgeLabel?: string;
  reviewLabel?: string;
  qtyDecreaseLabel?: string;
  qtyIncreaseLabel?: string;
  trustShippingText?: string;
  trustReturnText?: string;
  trustWarrantyText?: string;
  showProductBadge?: boolean;
  showBuyNow?: boolean;
  buyNowText?: string;
  breadcrumbHomeText?: string;
  showStickyBar?: boolean;
  stickyQtyUnitText?: string;
  stickyImageAlt?: string;
  sizeGuideDrawerTitle?: string;
  sizeGuideIntro?: string;
  sizeGuideRow1Label?: string;
  sizeGuideRow1Value?: string;
  sizeGuideRow2Label?: string;
  sizeGuideRow2Value?: string;
  sizeGuideNote?: string;
  sizeGuideCloseLabel?: string;
  showCrossSell?: boolean;
  crossSellTitle?: string;
  crossSellSubtitle?: string;
  crossSellAddedText?: string;
  crossSellSelectLabel?: string;
  crossSellSelectedLabel?: string;
  galleryPrevAriaLabel?: string;
  galleryNextAriaLabel?: string;
  galleryThumbsUpAriaLabel?: string;
  galleryThumbsDownAriaLabel?: string;
  detailsAnchorLabel?: string;
  favoriteAriaLabel?: string;
  favoriteRemoveAriaLabel?: string;
  shareAriaLabel?: string;
  linkCopiedText?: string;
  showPromotionCountdown?: boolean;
  promotionLabel?: string;
  promotionEndDate?: Date | string;
  promotionEndTime?: string;
  dayUnitLabel?: string;
  hourUnitLabel?: string;
  minuteUnitLabel?: string;
  secondUnitLabel?: string;
  promotionExpiredText?: string;
  promotionBackgroundColor?: string;
  promotionTextColor?: string;
  promotionAccentColor?: string;
  bundleTitle?: string;
  bundleSubtitle?: string;
  bundleQtyLabel?: string;
  reviewsAnchorLabel?: string;
  galleryPauseAriaLabel?: string;
  galleryPlayAriaLabel?: string;
  optionsRequiredErrorText?: string;
  optionsInvalidText?: string;
  optionsSelectPlaceholder?: string;
  optionsFileDropText?: string;
  optionsUploadingText?: string;
  optionsUploadFailedText?: string;
  optionsFileSizeErrorText?: string;
  optionsFileTypeErrorText?: string;
  optionsMaxFilesErrorText?: string;
  optionsMinLabelText?: string;
  optionsMaxLabelText?: string;
  optionsRemoveFileLabel?: string;
  optionsOptionalText?: string;
}
